---
- name: Add PPA
  apt_repository:
    repo: ppa:openjdk-r/ppa

- name: Build list of items to install
  set_fact:
    java_install_items: "{{ java_install_items }} +  ['openjdk-{{ openjdk_version }}-{{ item }}']"
  with_items: "{{ openjdk_types }}"

- name: Install OpenJDK
  apt:
    name: "{{ java_install_items }}"
